[project]
name = "counter"
authors = []
description = ""
telemetry = false
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.counter]
path = "contracts/counter.clar"
depends_on = []

[contracts.hou-token]
path = "contracts/hou-token.clar"
depends_on = ["sip009-nft-trait"]

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
depends_on = []
