[project]
name = "counter"
authors = []
description = ""
telemetry = false
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.counter]
path = "contracts/counter.clar"
depends_on = []
